name: Build Enterprise Edition

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build Windows Exe
    runs-on: windows-2022

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Clean Install
        env:
          npm_config_runtime: electron
          npm_config_target: 29.4.6
          npm_config_disturl: https://electronjs.org/headers
          npm_config_build_from_source: true
        run: |
          npm prune
          npm install

      - name: Build Enterprise App
        env:
          APP_MODE: ENTERPRISE
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run dist -- --publish never

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: SECURE-MSG-ENTERPRISE-FINAL
          path: dist/
          if-no-files-found: warn
